### PR TITLE
Rootless

### PR DESCRIPTION
**Pull request by cortopy**
> Please provide enough information so that others can review your pull request:

This PR is motivated by my recent PR https://github.com/frappe/frappe_docker/pull/422. It applies some changes that follow from it

> Explain the **details** for making this change. What existing problem does the pull request solve?

This PR brings a few customisation and enhanced security features:

- Containers are assumed to be running as rootless as default
- A service account is created for the redis workloads
- A new volume is added for the logs
- Some extra customisation possibilities for redis 
- Changes the default redis container to bitnami/redis. This brings it in line with the recommendation to use bitnami/mariadb in the docs. It's also safer as it doesn't require privileges and can run rootless for cluster with pod security policies

### CODE REVIEW

**Comment by revant** [comment]
I'll have to manually test the upgrade.

Can you confirm that there is no problem during `helm upgrade` from current version / templates?

Whenever I see PR here, I feel we should have a travis k3d job that does helm install current version (do basic site operations) and then upgrade it to the one from PR and do upgrade + site operations.

I'll anyway manually test it like this https://github.com/frappe/helm/issues/67, anyone else can also help and

**Comment by cortopy** [comment]
> I'll have to manually test the upgrade.
> 
> Can you confirm that there is no problem during `helm upgrade` from current version / templates? IF not it may need migration / upgrade section and I'll bump the helm chart with major version.
> 
> Whenever I see PR here, I feel we should have a travis k3d job that does helm install current version (do basic site operations) and then upgrade it to the one from PR and do upgrade + site operations.
> 
> I'll anyway manually test it like this #67, anyone else can also help.

I can confirm it's working for me. I expanded the number of default values quite a lot and they all have sane defaults that shouldn't introduce any breaking changes.

Having said that, I'm already using the new rootless containers as merged in the PR I linked. I don't know if that PR is already included in the official ERP images. If it isn't then this should wait until it is

**Comment by revant** [comment]
I faced this error

```
helm upgrade frappe-bench-v12 --namespace erpnext erpnext \
    --set mariadbHost=mariadb.mariadb.svc.cluster.local \
    --set persistence.storageClass=nfs
Error: UPGRADE FAILED: execution error at (erpnext/templates/pvc_logs.yaml:17:23): A valid .Values.persistence.logs.storageClass entry required!
```

**Comment by revant** [comment]
Can you send changes to gh-pages branch of this repo as well?

It'll update docs on helm.erpnext.com

**Pull request merged**
