### PR TITLE
Persist apps in deployment-gunicorn.yaml

### PR DESCRIPTION
**Pull request by MohammedNoureldin**
Enables the persistence of apps and custom

At the moment, if the administrator creates a custom app (or edited the code of an existing app for some reason), the changes will be lost as soon as the container restarts, therefore persisting the apps is important.

### CODE REVIEW

**Comment by MohammedNoureldin** [comment]
Partially related to https://github.com/frappe/helm/issues/174

**Comment by MohammedNoureldin** [comment]
Hi, @revant 

Could you review the changes here please?

**Comment by MohammedNoureldin** [comment]
I have just realized this is gonna cause an issue. `apps` content is part of the image itself, and mounting anything in the same folder will hide the content. Can we somehow fill the `apps` folder after running the container by the init container for example? Or is there any other approach to persist the changes made anywhere in `apps` folder?

**Comment by MohammedNoureldin** [comment]
Well apparently we have a fundamental problem with installing/creating apps here.

I tried to create a very simple basic app and install it. Or course, the pod cannot be restarted because the container has no systemd, but I tried to recreate the whole pod (after adding a pvc and mount manually to persist the folder of the app insides apps). I was able to install the app, but when trying to call ERPNext in the browser, it does not work and I see in the logs that:

> ModuleNotFoundError: No module named '<app name>'

Something should be done in this regard. Am I missing something?

**Comment by revant** [comment]
Please fork the helm chart and then make the app code mutable in your fork.

**Comment by MohammedNoureldin** [comment]
Thank you. Then https://github.com/frappe/helm/pull/176 can also be closed, if forking the image is the solution. I will give it a try.

**Comment by MohammedNoureldin** [comment]
Thanks a lot again for the link, @revant! It helped me a lot to understand how everything here works and I implemented group to role mapping for OIDC custom providers (like Keycloak), in addition to default role functionality.

I will post it here, maybe it will help somebody.

https://github.com/MohammedNoureldin/oidc_extended

**Comment by jammeska** [comment]
@revant I fork helm chart but still have same issue.

**Pull request closed without merging**
