### PR TITLE
Custom additional initContainer command job-create-site.yaml

### PR DESCRIPTION
**Pull request by MohammedNoureldin**
Allowing to execute an additional custom command in the initContainer adds more flexibility, the most important one is to "bench get-apps" before installing them.

### CODE REVIEW

**Comment by MohammedNoureldin** [comment]
Please let me know if you have any better approach to get and install custom apps.

**Comment by revant** [comment]
> "bench get-apps"

You haven't read the FAQ I think

I don't know why people come up with this?

Everyone wants mutable image like a vm!

Please spare me from here.

Help me quit maintain these repos! Then just burn them down with any magic your feel is right

**Comment by MohammedNoureldin** [comment]
Dear @revant,

I have no intend to make the image mutable. It is about finding a more flexible way to mutate and persist the content that deserves being changed and persistent.

I have been implementing a missing functionality in the OIDC implementation, but could not test it because of difficulties in getting the app installed. Thus I wanted to find maybe another flexible approach to get the apps installed. It seems at the moment not possible after skimming the whole Docker images because of their structure. No need to get excited, everyone here is trying to make the software better, from different perspectives.

**Comment by revant** [comment]
> No need to get excited, everyone here is trying to make the software better, from different perspectives.

This happens every time.

Everyone wants to execute bench get-app or bench build in containers and I'm getting tired of pointing to FAQ or other posts. I answer same thing everywhere in forum as well as in GitHub.

Everything keeps tagging me everywhere for that.

**Comment by MohammedNoureldin** [comment]
I understand that, @revant, and all (of course including me) appreciate and are very thankful your great job and support. And I know it is intensive trying to answer and maintain all requests. I appreciate your efforts mate.

Just in case anyone else came by to this issue, this link tells what to do exactly:

https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md

**Comment by revant** [comment]
> I have been implementing a missing functionality in the OIDC implementation

Fork frappe, make changes, use forked frappe instead of upstream frappe in custom image.

The thing you feel missing can be done through custom app.
It just needs callback endpoint to do custom role mapping and additional magic. E.g. https://github.com/castlecraft/microsoft_integration

**Comment by MohammedNoureldin** [comment]
Thank you for the summary and for the link! I will check that.

**Pull request closed without merging**
